# Generated by Django 5.2.12 on 2026-03-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={},
        ),
        migrations.RemoveField(
            model_name='card',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
