# Generated by Django 5.2.12 on 2026-03-20 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_options_remove_card_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('en', models.CharField(max_length=255)),
                ('ru', models.CharField(max_length=255)),
                ('uz', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='is_sms_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('sender_card_number', models.CharField(db_index=True, max_length=16)),
                ('receiver_card_number', models.CharField(db_index=True, max_length=16)),
                ('sender_card_expiry', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^(0[1-9]|1[0-2])/[0-9]{2}$', 'Format: MM/YY')])),
                ('sender_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('receiver_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('sending_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('currency', models.CharField(choices=[('860', 'UZS'), ('840', 'USD'), ('643', 'RUB')], default='860', max_length=3)),
                ('receiving_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=15, null=True)),
                ('state', models.CharField(choices=[('created', 'Created'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], db_index=True, default='created', max_length=15)),
                ('otp_hash', models.CharField(blank=True, editable=False, max_length=64, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('try_count', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ext_id'], name='cards_trans_ext_id_ade047_idx'), models.Index(fields=['sender_card_number', 'state'], name='cards_trans_sender__07ad63_idx')],
            },
        ),
    ]
