# Generated by Django 5.2.12 on 2026-03-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_error_card_is_sms_enabled_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
