# Generated by Django 5.2.12 on 2026-03-27 11:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cards', '0004_card_blocked_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('card_bind', 'Card Binding'), ('transfer', 'Money Transfer'), ('login', 'User Login')], max_length=20)),
                ('otp_hash', models.CharField(editable=False, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('try_count', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=150, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=150, verbose_name='Familiya')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('blocked_until', models.DateTimeField(blank=True, null=True, verbose_name='Bloklangan vaqti')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='transfer',
            name='cards_trans_ext_id_ade047_idx',
        ),
        migrations.RemoveIndex(
            model_name='transfer',
            name='cards_trans_sender__07ad63_idx',
        ),
        migrations.RemoveField(
            model_name='card',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='otp_expires_at',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='otp_hash',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='receiver_phone',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='sender_phone',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='try_count',
        ),
        migrations.AddField(
            model_name='otp',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.card'),
        ),
        migrations.AddField(
            model_name='otp',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.transfer'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_permission_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.user'),
        ),
        migrations.AddField(
            model_name='card',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.user'),
        ),
    ]
