# Generated by Django 5.2.12 on 2026-03-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_otp_user_alter_transfer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_hash',
            field=models.CharField(editable=False, max_length=6),
        ),
    ]
