# Generated by Django 5.2.12 on 2026-03-28 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_otp_otp_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='otp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='try_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otp',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_otps', to='cards.card'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_hash',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='otp',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_otps', to='cards.transfer'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='cards.user'),
        ),
    ]
