# Generated by Django 5.2.12 on 2026-03-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_card_otp_card_try_count_alter_otp_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='otp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='try_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
