# Generated by Django 5.2.12 on 2026-03-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_transfer_otp_transfer_try_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('blocked', 'Blocked'), ('deleted', 'Deleted')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(blank=True, choices=[('User Login', 'User Login'), ('Money Transfer', 'Money Transfer'), ('Card Block', 'Card Block'), ('Card Delete', 'Card Delete')], max_length=50, null=True),
        ),
    ]
