# Generated by Django 5.2.12 on 2026-03-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_alter_card_status_alter_otp_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(blank=True, choices=[('User Login', 'User Login'), ('Money Transfer', 'Money Transfer'), ('Card Block', 'Card Block'), ('Card Delete', 'Card Delete'), ('Card Binding', 'Card Binding')], max_length=50, null=True),
        ),
    ]
