# Generated by Django 5.2.12 on 2026-04-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_user_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
