# Generated by Django 5.2.12 on 2026-04-10 10:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_alter_user_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret_key',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True),
        ),
    ]
